#!/usr/bin/env python3

"""Alta3 Research || Author: RZFeeser@alta3.com"""

# function to push commands
def commandpush(devicecmd): #devicecmd is a list
    for coffetime in devicecmd.keys():
        print("Handshaking. .. ... connecting with " + coffeetime)
        #we'll learn to write code that connects to devices here
        for mycmds in devicecmd[coffeetime]:
            print("Attempting to sending command --> " + mycmds)
            #we'll learn to write code that send cmds to device here


def main():
    work2do = {"10.1.0.1":["interface eth1/2", "no shut"], "10.2.0.1":["interface eth1/1", "shutdown"]}

    print("welcome to the network device command pusher") #welcome message

    ### get data set
    print("\nData set found\n") # replace with function call that reads in data from file

    ##run 
    commandpush(work2do) #call function to push commands to devices


#call the main function
main()


